"use strict";

var fs        = require("fs");
var path      = require("path");
var Sequelize = require("sequelize");
var env      = process.env.NODE_ENV || "development";
var config    = require(__dirname + '/../config/config.json')[env];
var db        = {};
var sequelize;
var match;

if (process.env.DATABASE_URL) {
  match = process.env.DATABASE_URL.match(/postgres:\/\/([^:]+):([^@]+)@([^:]+):(\d+)\/(.+)/)

  sequelize = new Sequelize(match[5], match[1], match[2], {
    dialect:  'postgres',
    protocol: 'postgres',
    port:    match[4],
    host:    match[3],
    logging:  true //false
  });
} else {
  sequelize = new Sequelize(config.database, config.username, config.password, config);
}

fs
  .readdirSync(__dirname)
  .filter(function(file) {
    return (file.indexOf(".") !== 0) && (file !== "index.js");
  })
  .forEach(function(file) {
    var model = sequelize["import"](path.join(__dirname, file));
    db[model.name] = model;
  });

Object.keys(db).forEach(function(modelName) {
  if ("associate" in db[modelName]) {
    db[modelName].associate(db);
  }
});

db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;


db.Author.create({firstname: "Jeff", lastname: "Griggs"});
db.Author.create({firstname: "Phillip", lastname: "Pullman"});
db.Author.create({firstname: "Thomas", lastname: "Lewis"});
db.Author.create({firstname: "Ray", lastname: "Bradbury"});
db.Author.create({firstname: "Hermann", lastname: "Hesse"});
db.Author.create({firstname: "Norman", lastname: "Mailer"});
db.Author.create({firstname: "David", lastname: "Sedaris"});
db.Author.create({firstname: "James", lastname: "Baldwin"});
db.Author.create({firstname: "Don", lastname: "Paterson"});
db.Author.create({firstname: "Julian", lastname: "Barnes"});
db.Author.create({firstname: "Keith", lastname: "Johnstone"});
db.Author.create({firstname: "Malcolm", lastname: "X"});
db.Author.create({firstname: "John", lastname: "Maeda"});
db.Author.create({firstname: "Walter", lastname: "Isaacson"});
db.Author.create({firstname: "Tina", lastname: "Fey"});
db.Author.create({firstname: "Christopher", lastname: "McDougall"});
db.Author.create({firstname: "John", lastname: "Wooden"});


db.Book.create({title: "Guru: My Days With Del Close", AuthorId: 1});
db.Book.create({title: "The Golden Compass", AuthorId: 2});
db.Book.create({title: "The Subtle Knife", AuthorId: 2});
db.Book.create({title: "The Amber Spy Glass", AuthorId: 2});
db.Book.create({title: "A General Theory Of Love", AuthorId: 3});
db.Book.create({title: "Dandelion Wine", AuthorId: 4});
db.Book.create({title: "Siddhartha", AuthorId: 5});
db.Book.create({title: "Zen In The Art Of Writing", AuthorId: 4});
db.Book.create({title: "The Fight", AuthorId: 6});
db.Book.create({title: "Me Talk Pretty One Day", AuthorId: 7});
db.Book.create({title: "If Beale Street Could Talk", AuthorId: 8});
db.Book.create({title: "Best Thought, Worst Thought", AuthorId: 9});
db.Book.create({title: "The Sense Of An Ending", AuthorId: 10});
db.Book.create({title: "Impro", AuthorId: 11});
db.Book.create({title: "The Autobiography of Malcolm X", AuthorId: 12});
db.Book.create({title: "Redesigning Leadership", AuthorId: 13});
db.Book.create({title: "Steve Jobs", AuthorId: 14});
db.Book.create({title: "Bossypants", AuthorId: 15});
db.Book.create({title: "Born To Run", AuthorId: 16});
db.Book.create({title: "The Laws of Simplicity", AuthorId: 13});
db.Book.create({title: "Wooden", AuthorId: 17});


db.Quote.create({text: "Consider your scenes in improvisation in the same manner of rearing a child. The absolute worst thing you can do in either is to be apathetic...Lack of emotion is lethal. It will kill every scene. Love, anger, hatred, lust—all go a long way to show urgency, desire, and caring in every scene.", BookId: 1});
db.Quote.create({text: "It’s possible that the audience figured it out before you did, but by the time you finally spit it back to them they were bored and annoyed that it took you so long to catch up to them.", BookId: 1}); 
db.Quote.create({text: "Try to kill the audience. Fucking kill them. I want you to make them laugh so hard they vomit and choke on their own vomit.", BookId: 1});
db.Quote.create({text: "You need to consciously invest more concern in your scene partner than in yourself so that you can explore all the facets of your existence and environment.", BookId: 1});
db.Quote.create({text: "You have to treat your scene partners like artists and poets. When you lower yourself to play retards and obese people, you pander to the audience and you insult your scene partner, the audience, and me.", BookId: 1}); 
db.Quote.create({text: "Wear your characters like a trenchcoat.", BookId: 1});
db.Quote.create({text: "A thousand cheap laughs can never compare to one intelligent chuckle.", BookId: 1});
db.Quote.create({text: "Laughter is a response to a gestalt formation where two previously incompatible or dissimilar ideas suddenly form into a new piece of understanding. The energy release during that reaction comes out in laughter.", BookId: 1}); 
db.Quote.create({text: "To gain respect and succeed in this art form, play to the height of your intelligence. You can play an idiot or a retard, but strive to play the smartest retard that you possibly can.", BookId: 1});
db.Quote.create({text: "The key to teaching new students or students that have been taught incorrectly is to remain composed. Hostility and impatience only serve to stunt their growth. We have to realize that our mission today is not to erect the pyramid but to set up a solid foundation so that the construction can be completed effortlessly after we depart.", BookId: 1});
db.Quote.create({text: "My friends, you are all under the misconception that you are the most important person on the stage. You are not. Your scene partner is. You need to consciously invest more concern and respect for each other on stage. Humility and deference will take you farther than arrogance and selfishness.", BookId: 1}); 
db.Quote.create({text: "Start every scene in the middle.", BookId: 1});
db.Quote.create({text: "Don’t ever think this journey is about you. It’s about everyone around you.", BookId: 1});
db.Quote.create({text: "Lord Asriel was a tall man with powerful shoulders, a fierce dark face, and eyes that seemed to flash and glitter with savage laughter. It was a face to be dominated by, or to fight: never a face to patronize or pity. All his movements were large and perfectly balanced, like those of a wild animal, and when he appeared in a room like this, he seemed a wild animal held in a cage too small for it.", BookId: 2}); 
db.Quote.create({text: "...and he would sit back with one ankle resting on the other knee and watch her inscrutably until her words failed.", BookId: 2});
db.Quote.create({text: "Like a wave that has been building its strength over a thousand miles of ocean, and which makes little stir in the deep water, but which when it reaches the shallows rears itself up high into the sky, terrifying the shore dwellers, before crashing down on the land with irresistible power–so Iorek Gyrnison rose up against Iofur, exploding upward from his firm footing on the dry rock and slashing with a ferocious left hand at the exposed jaw of Iofur Raknison.", BookId: 2});
db.Quote.create({text: "But I can do it. Somewhere out there is the origin of all the Dust, all the death, the sin, the misery, the destructiveness in the world. Human beings can’t see anything without wanting to destroy it, Lyra. That’s original sin. And I’m going to destroy it. Death is going to die.", BookId: 2}); 
db.Quote.create({text: "So Lyra and her daemon turned away from the world they were born in, and looked toward the sun, and walked into the sky.", BookId: 2});
db.Quote.create({text: "I found folly everywhere, but there were grains of wisdom in every stream of it. No doubt there was much more wisdom that I failed to recognize. Life is hard, Mr. Scoresby, but we cling to it all the same.", BookId: 3});
db.Quote.create({text: "...and his face bore an expression that mingled haughty disdain with a tender, ardent sympathy, as if he would love all things if only his nature could let him forget their defects.", BookId: 4}); 
db.Quote.create({text: "He made himself quiet and dull-eyed and slow, and in under a minute he bacame less interesting, less attractive to human attention. The people simply became bored with this dull child, and forgot him and turned away.", BookId: 4});
db.Quote.create({text: "Instead of seeing only the wickedness and cruelty and greed of the ghosts that come down here, from now on you will have the right to ask all the ghosts to tell you the stories of their lives, and they will have to tell the truth about what they’ve seen and touched and heard and loved and known in the world. Every one of these ghosts has a story; every single one that comes down in the future will have true things to tell you about the world. And you’ll have the right to hear them, and they will have to tell you.", BookId: 4});
db.Quote.create({text: "Angel after angel, outlined in fire, their wings ablaze, tumbled screaming from the air.", BookId: 4}); 
db.Quote.create({text: "And at half past nine in the evening at that restaurant table in Portugal, someone gave me a piece of marzipan and it all came back. And I thought: am I really going to spend the rest of my life without ever feeling that again? I thought: I want to go to China. It’s full of treasure and strangeness and mystery and joy. I thought, will anyone be better off if I go straight back to the hotel and say my prayers and confess to the priest and promise never to fall into temptation again? Will anyone be the better for making me miserable? And the answer came back—no. No one will. There’s no one to fret, no one to condemn, no one to bless me for being a good girl, no one to punish me for being wicked. Heaven was empty. I didn’t know whether God had died, or whether there never had been a God at all. Either way I felt free and lonely and I didn’t know whether I was happy or unhappy, but something very strange had happened. And all that huge change came about as I had the marzipan in my mouth, before I’d even swallowed it. A taste—a memory—a landslide.", BookId: 4});
db.Quote.create({text: "I came to believe that good and evil are names for what people do, not for what they are. All we can say is that this is a good deed, because it helps someone, or that’s an evil one, because it hurts them. People are too complicated to have simple labels.", BookId: 4});
db.Quote.create({text: "What is worth having is worth working for.", BookId: 5}); 
db.Quote.create({text: "Love makes us who we are, and who we can become.", BookId: 5});
db.Quote.create({text: "Every book, if it is anything at all, is an argument.", BookId: 5});
db.Quote.create({text: "People who do not intuit or respect the laws of acceleration and momentum break bones; those who do not grasp the principles of love waste their lives and break their hearts.", BookId: 5}); 
db.Quote.create({text: "The questions we ask change the world we see.", BookId: 5});
db.Quote.create({text: "Those who wish to drink in the details, however, need not drown in them.", BookId: 5});
db.Quote.create({text: "The rapid demise of the reptilian giants left open opportunities for an upwardly mobile class. Mammals scurried into the gap and bred like the rabbits they were to become. Sixty-five million years later, the Age of Mammals is still in full swing.", BookId: 5}); 
db.Quote.create({text: "As E.E. Cummings observed: Always a more beautiful answer that asks a more beautiful question.", BookId: 5});
db.Quote.create({text: "Evolution is a kaleidoscope, not a pyramid: the shapes and variety of species are constantly shifting, but there is no basis for assigning supremacy, no pinnacle toward which the system is moving. Five hundred million years ago, every species was either adapted to that world or changing to become so. The same is true today. We are free to label ourselves the end product of evolution not because it is so, but because we exist now. Expunge this temperocentrist bias, and the neocortical brain is not the most advanced of the three, but simply the most recent.", BookId: 5});
db.Quote.create({text: "But in the words of a neocortical brain as mighty as Einstein’s: \“We should take care not to make the intellect our god; it has, of course, powerful muscles, but no personality. It cannot lead; it can only serve.\”", BookId: 5}); 
db.Quote.create({text: "A mood is a state of enhanced readiness to experience a certain emotion. Where an emotion is a single note, clearly struck, hanging for a moment in the still air, a mood is the extended, nearly inaudible echo that follows.", BookId: 5});
db.Quote.create({text: "The most common precipitant of this reiterant emotionality is cognition: people tend to think about emotionally arousing occasions afterward, recirculating the experience and stimulating the consequent emotion just as if the inciting event had actually re-occurred. The human penchant for this post hoc cogitation can magnify the physiologic impact of an emotion many times.", BookId: 5});
db.Quote.create({text: "\“Dream delivers us to dream, and there is no end to illusion. Life is a train of moods like a string of beads, and, as we pass through them, they prove to be many-colored lenses which paint the world their own hue...Temperament is the iron wire on which the beads are strung.\” - Ralph Waldo Emerson", BookId: 5}); 
db.Quote.create({text: "Short separations provoke an acute response known as protest, while prolonged separations yield the physiologic state of despair.", BookId: 5});
db.Quote.create({text: "The mammalian nervous system depends for its neurophysiologic stability on a system of interactive coordination, wherein steadiness comes from synchronization with nearby attachment figures...Evolution has given mammals a shimmering conduit, and they use it to tinker with one another’s physiology, to adjust and fortify one another’s fragile neural rhythms in the collaborative dance of love. We call this mutually synchronizing exchange limbic regulation.", BookId: 5});
db.Quote.create({text: "The reciprocal process occurs simultaneously: the first person regulates the physiology of the second, even as he himself is regulated. Neither is a functioning whole on his own; each has open loops that only somebody else can complete. Together they create a stable, properly balanced pair of organisms.", BookId: 5}); 
db.Quote.create({text: "That open-loop design means that in some important ways, people cannot be stable on their own – not should or shouldn’t be, but can’t be...Stability means finding people who regulate you well and staying near them.", BookId: 5});
db.Quote.create({text: "Full-grown, these monkeys are living proof of limbic regulation’s enduring power: they are timid, clingy, subordinate, and clumsy in their efforts to establish ties to other monkeys. The brains of these animals evidence permanent alterations in neurochemistry...With their vulnerability to anxiety and depression, their social awkwardness and failures to attach as adults, these monkeys exhibit a close animal counterpart to the multifaceted misery that in human beings is labeled neurotic.", BookId: 5});
db.Quote.create({text: "As a society, if we do not attend to the limbic needs of our own young, we risk creating an epidemic of loss vulnerability.", BookId: 5}); 
db.Quote.create({text: "We are attached to keep our brains on track, in a process that begins before birth and sustains life until its end. The earliest portion of that duet must catch our attention: attachment changes a young mammal forever, as limbic regulation carves enduring patterns of knowledge into the developing circuits of the mind.", BookId: 5});
db.Quote.create({text: "Since time’s beginning, romantic partners have searched for each other with exquisite but obscure deliberation...Not just anyone will do; in fact, to any one person looking for a mate, almost nobody will.", BookId: 5});
db.Quote.create({text: "Implicit memory ensures that camouflaged learning permeates our lives...Behind the familiar bright, analytic engine of consciousness is a shadow of silent strength, spinning dazzlingly complicated life into automatic actions, convictions without intellect, and hunches whose reasons follow later or not at all. It is this darker system that guides our choices in love.", BookId: 5}); 
db.Quote.create({text: "We play out our unconscious knowledge in every unthinking move we make in the dance of loving. If a child has the right parents, he learns the right principles – that love means protection, caretaking, loyalty, sacrifice. He comes to know it not because he is told, but because his brain automatically narrows crowded confusion into a few regular prototypes. If he has emotionally unhealthy parents, a child unwittingly memorizes the precise lesson of their troubled relationship: that love is suffocation, that anger is terrifying, that dependence is humiliating, or one of a million other crippling variations.", BookId: 5});
db.Quote.create({text: "Experience methodically rewires the brain, and the nature of what is has seen dictates what it can see.", BookId: 5});
db.Quote.create({text: "A network then registers novel sensory information as if it conformed to past experience. In much the same way, our sun’s blinding glare washes countless dimmer stars from the midday sky.", BookId: 5}); 
db.Quote.create({text: "The more often you do or think or imagine  thing, the more probable it is that your mind will revisit its prior stopping point. When the circuits are sufficiently well worn such that thoughts fly down them with little friction or resistance, that mental path has become a part of you – it is now a habit of speech, thought, action, attitude. Ongoing exposure to one person’s Attractors does not merely activate neural patterns in another – it also strengthens them. Long-standing togetherness writes permanent changes into a brain’s open book. In a relationship, one mind revises another; one heart changes its partner. This astounding legacy of our combined status as mammals and neural beings is limbic revision: the power to remodel the emotional parts of the people we love, as our Attractors activate certain limbic pathways, and the brain’s inexorable memory mechanism reinforces them. Who we are and who we become depends, in part, on whom we love.", BookId: 5});
db.Quote.create({text: "Everything a person is and everything he knows resides in the tangled thicket of his intertwined neurons. These fateful, tiny bridges number in the quadrillions, but they spring from just two sources: DNA and daily life. The genetic code calls some synapses into being, while experience engenders and modifies others.", BookId: 5});
db.Quote.create({text: "DNA is not the heart’s destiny; the genetic lottery may determine the cards in your deck, but experience deals the hand you can play.", BookId: 5}); 
db.Quote.create({text: "Emotional experience begins as a derivative; a child gets his first taste of his feelings secondhand. Only through limbic resonance with another can he begin to apprehend his inner world. The first few years of resonance prepare this instrument for a lifetime’s use.", BookId: 5});
db.Quote.create({text: "That concentrated knowledge whispers to a child from beneath the veil of consciousness, telling him what relationships are, how they function, what to anticipate, how to conduct them. If a parent loves him in the healthiest way, wherein his needs are paramount, mistakes are forgiven, patience is plentiful, and hurts are soothed as they can be, then that is how he will relate to himself and others.", BookId: 5});
db.Quote.create({text: "\"The real voyage of discovery consists not in seeking new landscapes, but in having new eyes.\" - Marcel Proust", BookId: 5}); 
db.Quote.create({text: "Every person broadcasts information about his inner world. As a collection of dense matter betrays its presence through electromagnetic emissions, a person’s emotional Attractors manifest themselves in a radiant aura of limbic tones. If a listener quiets his neocortical chatter and allows limbic sensing to range free, melodies begin to penetrate the static of anonymity. Inspanidual tales of reactions, hopes, expectations, and dreams resolve into themes. Stories about lovers, teachers, friends, and pets echo back and forth and coalesce into a handful of motifs. As the listener’s resonance grows, he will catch sight of what the other sees inside that personal world, start to sense what it feels like to live there.", BookId: 5});
db.Quote.create({text: "Psychotherapy changes people because one mammal can restructure the limbic brain of another...When a limbic connection has established a neural pattern, it takes a limbic connection to revise it.", BookId: 5});
db.Quote.create({text: "Self-help books are like car repair manuals: you can read them all day, but doing so doesn’t fix a thing.", BookId: 5}); 
db.Quote.create({text: "Against the odds, as it has since the beginning, life finds a way.", BookId: 5});
db.Quote.create({text: "What Richard Selzer, M.D., once wrote of surgery is as true of therapy: only human love keeps this from being the act of two madmen.", BookId: 5});
db.Quote.create({text: "People vary in their awareness of emotional imperatives. Those who grasp them live better lives; those who do not suffer inexorable consequences.", BookId: 5}); 
db.Quote.create({text: "\"The one thing in the world of value is the active soul – the soul free, sovereign, active. This every man is entitled to; this every man contains within him, although in almost all men, obstructed, and as yet unborn.\" - Ralph Waldo Emerson", BookId: 5});
db.Quote.create({text: "\"What a society honors will be cultivated.\" - Aristotle", BookId: 5});
db.Quote.create({text: "Government is the machine that transforms cultural attitudes into policies...We need only glance at our social programs to catch the direction of prevailing winds...Caught in the middle, American parenthood is beleaguered, belittled, and besieged.", BookId: 5}); 
db.Quote.create({text: "The emotional fate of children is inextricably bound to the ability of their parents to love one another – a skill that is falling into disrepair.", BookId: 5});
db.Quote.create({text: "Relationships live on time. They devour it in the way that bees feed on pollen or aerobic cells on oxygen: with an unbending singularity of purpose and possibility of compromise or substitution.", BookId: 5});
db.Quote.create({text: "\"If two people who love each other let a single instant wedge itself between them, it grows – it becomes a month, a year, a century; it becomes too late.\" - Jean Giraudoux", BookId: 5}); 
db.Quote.create({text: "If somebody must jettison a part of life, time with a mate should be last on the list: he needs that connection to live.", BookId: 5});
db.Quote.create({text: "All the waking moments of our love lives should tend, we are told, toward that throbbing, amorous apotheosis. But in love merely brings the players together, and the end of that prelude is as inevitable as it is desirable. True relatedness has a chance to blossom only with the waning of its intoxicating predecessor.", BookId: 5});
db.Quote.create({text: "Loving derives from intimacy, the prolonged and detailed surveillance of a foreign soul.", BookId: 5}); 
db.Quote.create({text: "Lovers hold keys to each other’s identities, and they write neurostructural alterations into each other’s networks. Their limbic tie allows each to influence who the other is and becomes.", BookId: 5});
db.Quote.create({text: "The prevailing myth reaching most contemporary ears is this: relationships are 50-50...Love is simultaneous mutual regulation, wherein each person meets the needs of the other, because neither can provide for his own. Such a relationship is not 50-50 – it’s 100-100.", BookId: 5});
db.Quote.create({text: "Because relationships are mutual, partners share a single fate: no action benefits one and harms the other. The hard bargainer, who thinks he can win by convincing his partner to meet his needs while circumventing hers, is doomed.", BookId: 5}); 
db.Quote.create({text: "Happiness is within range only for adroit people who give the slip to America’s values. These rebels will necessarily forgo exalted titles, glamorous friends, exotic vacations, washboard abs, designer everything – all the proud indicators of upward mobility – and in exchange, they may just get a chance at a decent life.", BookId: 5});
db.Quote.create({text: "Close early relationships instill a permanent resilience to the degenerative influence of stress, while neglect sensitizes children to those effects.", BookId: 5});
db.Quote.create({text: "\"When you love, you wish to do things for. You wish to sacrifice for. You wish to serve.\" - Ernest Hemingway", BookId: 5}); 
db.Quote.create({text: "\"Modern man is estranged from being, from his own being, from the being of other creatures in the world, from transcendent being. He has lost something – what, he does not know; he only knows that he is sick unto death with the loss of it.\" - Walker Percy", BookId: 5});
db.Quote.create({text: "In pursuit of further riches, the information age demands a more throughgoing surrender – less time for relationships, less time for children, more time for impersonal everything. Before our lives wither away into dust, we might ponder how much more prosperity human beings can possibly survive.", BookId: 5});
db.Quote.create({text: "The consequences that flow from limbic ignorance are as grim as love’s victories are miraculous. The tragedy lies, as all tragedy does, in the knowledge that these sad outcomes once held the potential for greatness.", BookId: 5}); 
db.Quote.create({text: "Limbic resonance, regulation, and revision define our emotional existence; they are the walls and towers of the neural edifice evolution has built for mammals to live in. Our intellect is largely blind to them.", BookId: 5});
db.Quote.create({text: "\"Reason’s last step is recognizing that an infinity of things surpass it.\" - Blaise Pascal", BookId: 5});
db.Quote.create({text: "And at last, slowly, afraid he would find nothing, Douglas opened one eye. And everything, absolutely everything, was there. The world, like a great iris of an even more gigantic eye, which has also just opened and stretched out to encompass everything, stared back at him. And he know what it was that had leaped upon him to stay and would not run away now. I’m alive, he thought.", BookId: 6}); 
db.Quote.create({text: "No matter how hard you try to be what you once were, you can only be what you are here and now. Time hypnotizes. When you’re nine, you think you’ve always been nine years old and will always be. When you’re thirty, it seems you’ve always been balanced there on that bright rim of middle life. And then when you turn seventy, you are always and forever seventy. You’re in the present, you’re trapped in a young now or an old now, but there is no other now to be seen.", BookId: 6});
db.Quote.create({text: "Be what you are, bury what you are not.", BookId: 6});
db.Quote.create({text: "They walked for a full minute in silence, looking at their feet. They came to a fence. \“Last one over this fence,\” said Douglas, \“is a girl.\” All the way home they called Douglass \“Dora.\”", BookId: 6}); 
db.Quote.create({text: "The first light on the roof outside; very early morning. The leaves on all the trees tremble with a soft awakening to any breeze the dawn may offer. And then, far off, around a curve of silver track, comes the trolley, balanced on four small steel-blue wheels, and it is painted the color of tangerines.", BookId: 6});
db.Quote.create({text: "\“Doom. Doom. You sound like a funeral bell tolling,\” said Grandfather. \“Talk like that is worse than swearing. I won’t wash out your mouth with soap, however. A thimbleful of dandelion wine is indicated. Here, now, swig it down. What’s it taste like?\” \“I’m a fire-eater! Whoosh!\” \“Now upstairs, run three times around the block, do five somersets, six pushups, climb two trees, and you’ll be concertmaster instead of chief mourner.", BookId: 6});
db.Quote.create({text: "\"I’ve always known that the quality of love was the mind, even though the body sometimes refuses this knowledge. The body lives for itself. It lives only to feed and wait for the night. It’s essentially nocturnal. But what of the mind which is born of the sun, William, and must spend thousands of hours of a lifetime awake and aware? Can you balance off the body, that pitiful, selfish thing of night against a whole lifetime of sun and intellect? I don’t know. I only know there has been your mind here and my mind here, and the afternoons have been like none I can remember. There is still so much to talk about, but we must save it for another time.\”", BookId: 6}); 
db.Quote.create({text: "Four o’clock in the afternoon. Flies dead on the pavement. Dogs wet mops in their kennels. Shadows herded under trees. Downtown stores shut up and locked. The lake shore empty. The lake full of thousands of people up to their necks in the warm but soothing water.", BookId: 6});
db.Quote.create({text: "Douglas’s mouth was slightly open and from his lips and from the thin vents of his nostrils, gently there rose a scent of cool night and cool water and cool white snow and cool green moss, and cool moonlight on silver pebbles liying at the bottom of a quiet river and cool clear water at the bottom of a small white stone well. It was like holding their heads down for a brief moment to the pulse of an apple-scented fountain flowing cool up into the air and washing their faces. They could not move for a long time.", BookId: 6});
db.Quote.create({text: "He was animal, carcass, stone, wood, water, and each time he reawakened. The sun or moon shone, he was again Self, swung into the life cycle, felt thirst, conquered thirst, felt new thirst.", BookId: 7}); 
db.Quote.create({text: "Whether it is good or evil, whether life in itself is pain or pleasure, whether it is uncertain–that it may perhaps be this is not important–but the unity of the world, the coherence of all events, the embracing of the big and the small from the same stream, from the same law of cause, of becoming and dying: this shines clearly from your exalted teachings.", BookId: 7});
db.Quote.create({text: "...when you throw a stone into the water, it finds the quickest way to the bottom of the water. It is the same when Siddhartha has an aim, a goal. Siddhartha does nothing; he waits, he thinks, he fasts, but he goes through the affairs of the world like the stone through the water, without doing anything, without bestirring himself; he is drawn by his goal, for he does not allow anything to enter his mind which opposes his goal. That is what Siddhartha learned from the Samanas. It is what fools call magic and what they think is caused by demons. Nothing is caused by demons; there are no demons. Everyone can perform magic, everyone can reach his goal, if he can think, wait, and fast.", BookId: 7});
db.Quote.create({text: "Writing is good, thinking is better. Cleverness is good, patience is better.", BookId: 7}); 
db.Quote.create({text: "Most people are...are like a falling leaf that drifts and turns in the air, flutters, and falls to the ground. But a few others are like stars which travel one defined path: no wind reaches them, they have within themselves their guide and path.", BookId: 7});
db.Quote.create({text: "He learned from [the river] continually. Above all, he learned from it how to listen, to listen with a still heart, with a waiting, open soul, without passion, without desire, without judgment, without opinions.", BookId: 7}); 
db.Quote.create({text: "That the river is everywhere at the same time, at the source and at the mouth, at the waterfall, at the ferry, at the current, in the ocean and in the mountains, everywhere, and that the present only exists for it, not the shadow of the past, nor the shadow of the future?", BookId: 7});
db.Quote.create({text: "But stronger than his knowledge was his love for [his son], his devotion, his fear of losing him. had he ever lost his heart to anybody so completely, had he ever loved anybody so much, so blindly, so painfully, so hopelessly and yet so happily?", BookId: 7});
db.Quote.create({text: "Their vanities, desires and trivialities no longer seemed absurd to him; they had become understandable, lovable, and even worthy of respect. There was the blind love of a mother for her child, the blind foolish pride of a fond father for his only son, the blind eager strivings of a young vain woman for ornament and the admiration of men. All these little simple, foolish, but tremendously strong, vital, passionate urges and desires no longer seemed trivial to Siddhartha. For their sake he saw people live and do great things, travel, conduct wars, suffer and endure immensely, and he loved them for it. He saw life, vitality, the indestructible and Brahman in all their desires and needs. These people were worthy of love and admiration in their blind loyalty, in the blind strength and tenacity.", BookId: 7}); 
db.Quote.create({text: "The men of the world were equal to the thinkers in every other respect and were often surperior to them, just as animals in their tenacious undeviating actions in cases of necessity may often seem superior to human beings.", BookId: 7});
db.Quote.create({text: "Within Siddhartha there slowly grew and ripened he knowledge of what wisdom really was and the goal of his long seeking. It was nothing but a preparation of the soul, a capacity, a secret art of thinking, feeling, and breathing thoughts of unity at every moment of life.", BookId: 7}); 
db.Quote.create({text: "Wisdom is not communicable. The wisdom which a wise man tries to communicate always sounds foolish...Knowledge can be communicated, but not wisdom. One can find it, live it, be fortified by it, do wonders through it, but one cannot communicate and teach it.", BookId: 7});
db.Quote.create({text: "And Govinda saw that this mask-like smile, this smile of unity over the flowing forms, this smile of simultaneousness over the thousands of births and deaths...was exactly the same as the calm, delicate, impenetrable, perhaps gracious, perhaps mocking, wise, thousand-fold smile of Gotama, the Buddha.", BookId: 7});
db.Quote.create({text: "Yell. Jump. Play. Out-run those sons-of-bitches. They’ll never live the way you live. Go do it.", BookId: 8}); 
db.Quote.create({text: "We must take arms each and every day, perhaps knowing that the battle cannot be entirely won, but fight we must, if only a gentle bout. The smallest effort to win means, at the end of each day, a sort of victory.", BookId: 8});
db.Quote.create({text: "Remember the pianist who said that if he did not practice every day he would know, if he did not practice for two days, the critics would know, after three days, his audiences would know.", BookId: 8}); 
db.Quote.create({text: "Read poetry every day of your life. Poetry is good because it flexes muscles you don’t use often enough. Poetry expands the senses and keeps them in prime condition.", BookId: 8});
db.Quote.create({text: "The constant remains: the search, the finding, the admiration, the love, the honest response to materials at hand, no matter how shabby they one day seem, when looked back on.", BookId: 8});
db.Quote.create({text: "Do not, for money, turn away from all the stuff you have collected in a lifetime. Do not, for the vanity of intellectual publications, turn away from what you are – the material within you which makes you inspanidual, and is therefore indispensable to others.", BookId: 8}); 
db.Quote.create({text: "To feed your Muse, then, you should always have been hungry about life since you were a child. If not, it is a little late to start. Better late than never, of course. Do you feel up to it?", BookId: 8});
db.Quote.create({text: "Be certain of this: When honest love speaks, when true admiration begins, when excitement rises, when hate curls like smoke, you need never doubt that creativity will stay with you for a lifetime.", BookId: 8}); 
db.Quote.create({text: "Who are your friends? Do they believe in you? Or do they stunt your growth with ridicule and disbelief? If the latter, you haven’t friends. Go find some.", BookId: 8});
db.Quote.create({text: "To feed well is to grow. To work well and constantly is to keep what you have learned and know in prime condition.", BookId: 8});
db.Quote.create({text: "From these primitive bricks I have built a life and career. By my staying in love with all of these amazing things, all of the good things in my existence have come about.", BookId: 8}); 
db.Quote.create({text: "Those are not my friends, the ones who got me to tear the strips apart and so tear my own life down the middle; they are my enemies.", BookId: 8});
db.Quote.create({text: "I came on the old and best ways of writing through ignorance and experiment and was startled when truths leaped out of bushes like quail before gunshot. I blundered into creativity as blindly as any child learning to walk and see. I learned to let my senses and my Past tell me all that was somehow true.", BookId: 8}); 
db.Quote.create({text: "Why and how? Because I say it is so.", BookId: 8});
db.Quote.create({text: "You can’t have one without the other. No fantasy, no reality. No studies concerning loss, no gain. No imagination, no will. No impossible dreams, no possible solutions.", BookId: 8});
db.Quote.create({text: "No tension, it follows, aesthetically as well as practically, must be built which remains unreleased. Without this, any art ends incomplete, halfway to its goal. And in real life, as we know, the failure to relax a particular tension can lead to madness.", BookId: 8}); 
db.Quote.create({text: "No, I don’t want to handle that many people. A director has got to make forty or fifty people love him or fear him, or a combination of both, all the time. And how do you handle that many people and keep your sanity and your politeness? I’m afraid I would be impatient, which I wouldn’t want to be.", BookId: 8});
db.Quote.create({text: "You treat ideas like cats: you make them follow you. If you try to approach a cat and pick it up, hell, it won’t let you do it. You’ve got to say, \“Well, to hell with you.\” And the cat says, \“Wait a minute. He’s not behaving the way most humans do.\” Then the cat follows you out of curiosity: \“Well, what’s wrong with you that you don’t love me?\” Well, that’s what an idea is. See? You just say, \“Well, hell, I don’t need depression. I don’t need worry. I don’t need to push.\” The ideas will follow me. When they’re off-guard, and ready to be born, I’ll turn around and grab them.", BookId: 8}); 
db.Quote.create({text: "It is a lie to write in such a way as to be rewarded by money in the commercial market. It is a lie to write in such a way as to be rewarded by fame offered you by some snobbish quasi-literary group in the intellectual gazettes.", BookId: 8});
db.Quote.create({text: "For I believe that eventually quantity will make for quality. How so? ...An athlete may run ten thousand miles in order to prepare for one hundred yards. Quantity gives experience. From experience alone can quality come. All arts, big and small, are the elimination of waste motion in favor of the concise declaration. The artist learns what to leave out.", BookId: 8});
db.Quote.create({text: "Doing is being. To have done’s not enough; To stuff yourself with doing – that’s the game. To name yourself each hour by what’s done, To tabulate your time at sunset’s gun, And find yourself in acts, You could not know before the facts, You wooed from secret self, which much needs wooing, So doing brings it out, Kills doubt by simply jumping, rushing, running, Forth to be, The now-discovered me. To not do is to die, Or lie about and lie about the things. You just might do some day. Away with that! Tomorrow empty stays. If no man plays it into being. With his motioned way of seeing. Let your body lead your mind – Blood the guide dog to the blind; So then practice and rehearse. To find heart-soul’s universe, Knowing that by moving/seeing. Proves for all time: Doing’s being!", BookId: 8}); 
db.Quote.create({text: "There had been a temptation these last few days to take another walk around the partition on the balcony, only this time do it sober. He had resolutely refused to get into the stunt again, but knew the price: the sense of force within himself would diminish. He even felt a bit of shame at rooting for Ali if he was not ready to take this small dare with himself.", BookId: 9});
db.Quote.create({text: "Whether he was born with the philosophy or acquired it, his faith was that no advantage could prove too small to take.", BookId: 9}); 
db.Quote.create({text: "Confidence on both sides makes for war.", BookId: 9});
db.Quote.create({text: "His dreams he did not remember.", BookId: 9}); 
db.Quote.create({text: "The shocking disappearance of his possession had disturbed his vital force. \“His peaceful enjoyment of life\” had been \“wounded.\” The payment, therefore, was to recognize his natural rights to a \“restoration of being.\” Both chiefs understood the transaction perfectly. We are speaking of the economy of mood.", BookId: 9}); 
db.Quote.create({text: "We lacked the ability to think for ourselves and resented having to admit it.", BookId: 10});
db.Quote.create({text: "Part of the problem is that we live in the wrong part of town. SoHo is not a macaroni salad kind of place. This is where the world’s brightest young talents come to braise carmelized racks of corn-fed songbirds or offer up their famous knuckle of flash-seared crappie served with a collar of chided ginger and cornered by a tribe of kiln-roasted Chilean toadstools, teased with a warm spray of clarified musk oil. Even when they promise something simple, they’ve got to tart it up – the meatloaf has been poached in seawater, or there are figs in the tuna salad. If cooking is an art, I think we’re in our Dada phase.", BookId: 10}); 
db.Quote.create({text: "They were so free that they believed in nothing; and didn’t realize that this illusion was their only truth and that they were doing exactly as they had been told.", BookId: 11});
db.Quote.create({text: "Fonny: chews on the rib, and watches me: and, in complete silence, without moving a muscle, we are laughing with each other. We are laughing for many reasons. We are together somewhere where no one can reach us, touch us, joined. We are happy, even, that we have food enough for Daniel, who eats peacefully, not knowing that we are laughing, but sensing that something wonderful has happened to us, which means that wonderful things happen, and that maybe something wonderful will happen to him. It’s wonderful, anyway, to be able to help a person to have that feeling.", BookId: 11});
db.Quote.create({text: "I know I can’t help you very much right now – God knows what I wouldn’t give if I could. But I know about suffering; if that helps. I know that it ends. I ain’t going to tell you no lies, like it always ends for the better. Sometimes it ends for the worse. You can suffer so bad that you can be driven to a place where you can’t ever suffer again: and that’s worse.", BookId: 11}); 
db.Quote.create({text: "I don’t want to sound foolish. But, just remember, love brought you here. If you trusted love this far, don’t panic now.", BookId: 11});
db.Quote.create({text: "Every day, when he sees my face, he knows, again, that I love him – and God knows I do, more and more, deeper and deeper, with every hour. But it isn’t only that. It means that others love him, too, love him so much that they have set me free to be there. He is not alone; we are not alone.", BookId: 11});
db.Quote.create({text: "We live in a human dream; being one in which everything appears purely in the guise of its human utility, and held in place by its human name. Names are small and sinister metaphors which restrict, absolutely, the use of an object. Our eyes open to this madness every morning, and at night we dream within the dream; whole lives are spent without as much as a ripple of doubt on its surface. But when the object is allowed to shrug off its name, it begins the long road back to its mystery  – and on finally reaching the core of its own estranging fire, radiates until the whole world is unified by it. The rose or the paperclip; either could open the path back to our awakening.", BookId: 12}); 
db.Quote.create({text: "Everything in nature we don’t understand we once called miraculous.", BookId: 12});
db.Quote.create({text: "No matter how beautiful it is, if it appears in the wrong month: kill it.", BookId: 12});
db.Quote.create({text: "Mediocre art is far worse than bad. Bad art does not waste our time.", BookId: 12}); 
db.Quote.create({text: "We learn from history and repeat it cheerfully. History does not caution; it sanctions.", BookId: 12});
db.Quote.create({text: "No fury more righteous than that of a sinner accused of the wrong sin.", BookId: 12}); 
db.Quote.create({text: "In some Neanderthal part of me, every husband poses an affront.", BookId: 12});
db.Quote.create({text: "W. miscalculated. He thought he was overexposed., and would be valued for his rare appearances. Within a year they had forgotten him.", BookId: 12});
db.Quote.create({text: "We’re forever reading atrocities as mere omens; anything to do nothing a little while longer.", BookId: 12}); 
db.Quote.create({text: "In any other religion one would be shaken by a master’s failure – so what is it about the falls from grace of Chogyam Trungpa and Sogyal Rinpoche that seem to validate their teaching? Just as the destruction of the Bamiyan Buddhas was a glorious lesson in transience; a reminder that there is no one worth following, only paths.", BookId: 12});
db.Quote.create({text: "The insane enthusiasm of a nursery gardener who prunes his roses long before they flower, even the very buds...the brutal aesthetic of the bare branch and the thorn...to think what a vicious, perfect bloom this strain would immediately bring forth were we simply to allow it!", BookId: 12});
db.Quote.create({text: "The language of the angels and of the blessed consists of a single verb, possessing an infinite number of tenses, moods, and conjugations. In the language of the damned, every word is a part of speech entirely unrelated to any other; this tongue is the subject of enforced study for those wretches, who, under the scourge of the infernal grammarians, are condemned forever to the memorization of vast and endless textbooks. The two languages are, of course, precisely the same, the only difference being that this knowledge is withheld from the latter party.", BookId: 12}); 
db.Quote.create({text: "We grow into our prophesies. Often it is the simple embarrassment of having told everyone we will leave our lover that gives us the courage to do so; but this example calls a deeper system from the shadows. Usually we must open up the path before we can follow it, the air standing – all too often – solid against us. On those occasions we send out the god in ourselves, and follow his empty trail to our salvation. This is why transition so often feels like abandonment.", BookId: 12});
db.Quote.create({text: "The first procedure of good style is the inversion of the form in which the idea occurred to the thinker.", BookId: 12});
db.Quote.create({text: "With your back to the wall, always pay a compliment. Even your mugger or torturer is not immune to flattery, and still capable of being a little disarmed by a word of congratulation on their choice of footwear or superior technique.", BookId: 12}); 
db.Quote.create({text: "Whale to the ocean, bird to the sky, man to his dream.", BookId: 12});
db.Quote.create({text: "Your manifest uncertainty is the best guarantor of the truth of your statement, not your wise voice.", BookId: 12}); 
db.Quote.create({text: "Doors, those merciful conceits, those blind eyes of the house...As if your daughter or brother or friend isn’t beating off or taking a shit six feet from where you stand.", BookId: 12});
db.Quote.create({text: "With friends and strangers I can be no one; more and more I confine myself to their company. Then one day I enter a room full of acquaintances, and fly into a blind panic: I cannot remember for the life of me who these people think I am...", BookId: 12});
db.Quote.create({text: "The worst thing about thinking nothing of yourself is that you assume that your behavior has no consequence. This makes you much more dangerous than the egomaniac, who at least spends all his time calculating for his own effect.", BookId: 12}); 
db.Quote.create({text: "I suspect the real “trick” – if indeed it is a trick – with women is: 2) simply to love their company, and be unable to disguise it; and b) be confident enough either in yourself or your other arrangements genuinely not to care overmuch whether they will sleep with you or not. Feigned indifference is hopeless, and transparent. Desperation stinks to most women. But your visibly not hanging on the outcome of the evening is often a red rag to a bull.", BookId: 12});
db.Quote.create({text: "Only the mad are safe from doubt. I am always bewildered by those who regard a revised opinion as a sign of weakness; it strikes me as a fine guarantee of the commentator’s sanity.", BookId: 12});
db.Quote.create({text: "The poorest are denied their nostalgias by their social immobility. Their primal territories are the ones they still inhabit. Their sweetest memories are all ungeographic.", BookId: 12}); 
db.Quote.create({text: "Speed up its evolution, and it becomes clear that the eye is not a receptive aperture but an exit wound, the catastrophic projectile fire of mind into the world.", BookId: 12});
db.Quote.create({text: "An exhibition of Dutch art: Rubens has everything leaning this way, or that way, with all the dynamic nuance of a Walt Disney. And then Vincent, who always understood that there are always at least three different winds in the sky, and that the hellish intricacy of their interaction is the reason we cannot hope to comprehend the motive or forces driving anything. All those chairs and bathtubs and cars and shoes which, emptied of us, are immediately returned to absurdity. How many lonely things we make for the world.", BookId: 12});
db.Quote.create({text: "Consciousness can no more unmask its own nature than the eye can see itself. It is contractually blind.", BookId: 12}); 
db.Quote.create({text: "Memory is what we’d thought we’d forgotten.", BookId: 13});
db.Quote.create({text: "But time...how time first grounds us and then confounds us. We thought we were being mature when we were only being safe. We imagined we were being responsible but were only being cowardly. What we called realism turned out to be a way of avoiding things rather than facing them. Time...give us enough time and our best-supported decisions will seem wobbly, our certainties whimsical.", BookId: 13}); 
db.Quote.create({text: "In one moment I knew that the valuing of men by their intelligence is crazy, that the peasants watching the night sky might feel more than I feel, that the man who dances might be superior to myself – word-bound and unable to dance. From then on I noticed how warped many people of great intelligence are, and I began to value people for their actions, rather than their thoughts.", BookId: 14});
db.Quote.create({text: "I began to think of children not as immature adults, but of adults as atrophied children.", BookId: 14});
db.Quote.create({text: "In my view the man who falls on the banana skin is funny only if he loses status, and if we don’t have sympathy for him.", BookId: 14}); 
db.Quote.create({text: "Ten Golden Rules for Number Ones: 1) You must clearly display the trappings, postures, and gestures of dominance. 2) In moments of active rivalry you must threaten your subordinates aggressively. 3) In moments of physical challenge you (or your delegates) must be able forcibly to overpower your subordinates. 4) If a challenge involves brain rather than brawn you must be able to outwit your subordinates. 5) You must suppress squabbles that break out between your subordinates. 6) You must reward your immediate subordinates by permitting them to enjoy the benefits of their high ranks. 7) You must protect the weaker members of the group from undue persecution. 8) You must make decisions concerning the social activities of your group. 9) You must reassure your extreme subordinates from time to time. 10) You must take the initiative in repelling threats or attacks arising from outside your group.", BookId: 14});
db.Quote.create({text: "Students need a \“guru\” who \“gives permission\” to allow forbidden thoughts into their consciousness...All reassure by example. They are people who have been into the forbidden areas and who have survived unscathed.", BookId: 14});
db.Quote.create({text: "Those who say \“Yes\” are rewarded by the adventures they have, and those who say \“No\” are rewarded by the safety they attain.", BookId: 14}); 
db.Quote.create({text: "If you’ll think of something you wouldn’t want to happen to you, or to someone you love, then you’ll have thought of something worth staging or filming.", BookId: 14});
db.Quote.create({text: "The stages I try to take students through involve the realization 1) that we struggle against our own imaginations, especially when we try to be imaginative; 2) that we are not responsible for the content of our imaginations; and 3) that we are not, as we are taught to think, our \“personalities\”, but that the imagination is our true self.", BookId: 14});
db.Quote.create({text: "An artist has to accept what his imagination gives him, or screw up his talent.", BookId: 14}); 
db.Quote.create({text: "I say \“Free associate\”, and then when they’ve produced unconnected material, I say \“Connect\”, or \“Reincorporate\”...it encourages you to write whatever you feel like; it also means that you look back when you get stuck, instead of searching forwards. You look for things you’ve shelved, and then reinclude them.", BookId: 14});
db.Quote.create({text: "When you travel through darkness, hold love tightly, for you will need all the strength of your love to be unafraid of death.", BookId: 14}); 
db.Quote.create({text: "The people who love themselves cannot melt their own snow. Only you can melt my snow, for our love can never fail, for however cold it becomes, we shall love each other and therefore melt each other’s snows and live forever.", BookId: 14});
db.Quote.create({text: "Love is permanent only when friendship and trust exists. If friendship is transient, trust must be the permanent basis of love.", BookId: 14});
db.Quote.create({text: "He shouldn’t really think of making up stories, but of interrupting routines.", BookId: 14}); 
db.Quote.create({text: "A mask is a device for driving the personality out of the body and allowing a spirit to take possession of it.", BookId: 14});
db.Quote.create({text: "Anytime you find someone more successful than you are, especially when you’re both engaged in the same business – you know they’re doing something that you aren’t.", BookId: 15});
db.Quote.create({text: "The main thing you got to remember is that everything in the world is a hustle.", BookId: 15}); 
db.Quote.create({text: "Even then, I had learned enough about women to know not to pressure them when they’re thinking something out; they’ll tell you when they’re ready.", BookId: 15});
db.Quote.create({text: "More wives could keep their husbands if they realized their greatest urge is to be men.", BookId: 15});
db.Quote.create({text: "In order to get something you had to look as though you already had something.", BookId: 15}); 
db.Quote.create({text: "He had never been able to keep a white woman any length of time, though, because he was too good to them, and, as I have said, any woman, black or white, seems to get bored with that.", BookId: 15});
db.Quote.create({text: "This fence always sent your money in crisp, brand new bills. He was smart. Somehow that had a very definite psychological effect upon all of us.", BookId: 15}); 
db.Quote.create({text: "In any organization, someone must be the boss. If it’s even just one person, you’ve got to be the boss of yourself.", BookId: 15});
db.Quote.create({text: "All of our experiences fuse into our personality. Everything that ever happened to us is an ingredient.", BookId: 15});
db.Quote.create({text: "I read aimlessly, until I learned to read selectively, with a purpose.", BookId: 15}); 
db.Quote.create({text: "\“You never know what anything can do – until it is set free, to act by itself.\” - Elijah Muhammad", BookId: 15});
db.Quote.create({text: "If you ever intend to do anything worthwhile, you have to start with a worthwhile plan.", BookId: 15});
db.Quote.create({text: "\“No man has believed perfectly until he wishes for his brother what he wishes for himself.\” - Dr. Mahmoud Youssef Shawarbi", BookId: 15}); 
db.Quote.create({text: "I have always kept an open mind, which is necessary to the flexibility that must go hand in hand with every form of intelligent search for truth.", BookId: 15});
db.Quote.create({text: "Mankind’s history has proved from one era to another that the true criterion for leadership is spiritual.", BookId: 15});
db.Quote.create({text: "In all our deeds, the proper value and respect for time determines success or failure.", BookId: 15}); 
db.Quote.create({text: "In life, nothing is permanent; not even life itself.", BookId: 15});
db.Quote.create({text: "\“Above up, there is something even higher above up.\” - Japanese saying", BookId: 16});
db.Quote.create({text: "Being prepared isn’t a matter of how much you practice. It’s about knowing that even if you fail, you won’t give up.", BookId: 16}); 
db.Quote.create({text: "You can always learn when you’re not willing to give up seeking out something new.", BookId: 16});
db.Quote.create({text: "Work is much easier when its just work; it’s much harder when you actually care.", BookId: 16});
db.Quote.create({text: "\“All artists yearn to struggle. Without it, they don’t feel alive.\” - Jessie Shefrin", BookId: 16}); 
db.Quote.create({text: "Leading by doing ceases to be leading when you are doing more than leading.", BookId: 16});
db.Quote.create({text: "\“John, don’t think about MIT. Think about the world. Broaden your focus as far as possible.\” - Whitman Richards", BookId: 16});
db.Quote.create({text: "Watching something being made is a powerful way to understand a concept; trying to decode just the final result, no matter how simple and visually elegant, demands an explanation of how it came to be.", BookId: 16}); 
db.Quote.create({text: "I’d rather be green and growing instead of ripe, ready to rot.", BookId: 16});
db.Quote.create({text: "\“Stories trump statistics.\” - Zainab Salbi", BookId: 16});
db.Quote.create({text: "A leader’s job is to get people on board with his vision – and he’ll try whatever tools are at his disposal to do it.", BookId: 16}); 
db.Quote.create({text: "Transparency is great, but it doesn’t necessarily provide clarity.", BookId: 16});
db.Quote.create({text: "“For example” is an exemplary tool for achieving clarity", BookId: 16});
db.Quote.create({text: "Enter a room as a speaker and assume that the audience is non-English speaking.", BookId: 16}); 
db.Quote.create({text: "What you say in words, numbers, or pictures matters less than how you come across as a human being.", BookId: 16});
db.Quote.create({text: "Finding, knowing, and owning the respect that each audience deserves is the place where real communication is born.", BookId: 16});
db.Quote.create({text: "Tell us all why you are here in one sentence.", BookId: 16}); 
db.Quote.create({text: "The only way a leader has a chance to connect is to start by revealing his own humanity.", BookId: 16});
db.Quote.create({text: "When the right people are all in the right room with the right timing they can make the right decision...right now.", BookId: 16});
db.Quote.create({text: "I’ve learned that in building my own team that it’s the ultimate responsibility of the leader to ensure that his team consists of the right members for the job at hand.", BookId: 16}); 
db.Quote.create({text: "Knowing our limitations is what makes us human; ignoring them is what helps us believe we can lead.", BookId: 16});
db.Quote.create({text: "Entitlement is the path furthest away from enlightenment.", BookId: 16});
db.Quote.create({text: "Respect is constantly earned, and shouldn’t be assumed because of your position.", BookId: 16}); 
db.Quote.create({text: "Saying you are sorry is meaningful only if your ego has left the room.", BookId: 16});
db.Quote.create({text: "Time may tick in seconds, but life is lived in years.", BookId: 16});
db.Quote.create({text: "Positive acts often go unrewarded; negative acts always remain unforgotten. The choice is yours.", BookId: 16});
db.Quote.create({text: "\“The key to being a good manager is keeping the people who hate you away from those that are still undecided.\” - Casey Stengel", BookId: 16});
db.Quote.create({text: "\“He had the attitude that he could do anything, and therefore so can you. He put his life in my hands. So that made me do something I didn’t think I could do.\” - Elizabeth Holmes", BookId: 17});
db.Quote.create({text: "\“If you act like you can do something, then it will work. Pretend to be completely in control and people will assume that you are.\” - Nolan Bushnell", BookId: 17});
db.Quote.create({text: "\“In the first thirty years of your life, you make your habits. For the last thirty years of your life, you habits make you.\” - Old Hindu saying", BookId: 17});
db.Quote.create({text: "\“He believed that great harvests came from arid sources, pleasure from restraint. He knew the equations that most people didn’t know: Things led to their opposites.\” - Lisa Brennan Jobs", BookId: 17});
db.Quote.create({text: "\“I am a reflection of what I do.\” - Steve Jobs", BookId: 17});
db.Quote.create({text: "\“You’ve got to be like a butterfly and have a metamorphosis.\” - Mike Markkula", BookId: 17});
db.Quote.create({text: "\“Deciding what not to do is as important as deciding what to do.\” - Steve Jobs", BookId: 17});
db.Quote.create({text: "\“Our method was to develop integrated products, and that meant our process had to be integrated and collaborative.\” - Steve Jobs", BookId: 17});
db.Quote.create({text: "\“You need to have a collaborative hiring process.\” - Steve Jobs", BookId: 17});
db.Quote.create({text: "\“There’s a temptation in our networked age to think that ideas can be developed by email and iChat. That’s crazy. Creativity comes from spontaneous meetings, from random discussions. You run into someone, you ask what they’re doing, you say ‘Wow,’ and soon you’re cooking up all sorts of ideas.\” - Steve Jobs", BookId: 17});
db.Quote.create({text: "Nobody is eager for a lecture, but everybody loves a story.", BookId: 17});
db.Quote.create({text: "\“The heaviness of being successful was replaced by the lightness of being a beginner again, less sure about everything.\” - Steve Jobs", BookId: 17});
db.Quote.create({text: "\“Remembering that I’ll be dead soon is the most important tool I’ve ever encountered to help me make the big choices in life. Because almost everything – all external expectations, all pride, all fear of embarrassment or failure – these things just fall away in the face of death, leaving only what is truly important. Remembering that you are going to die is the best way I know to avoid the trap of thinking you have something to lose. You are already naked. There is no reason not to follow your heart.\” - Steve Jobs", BookId: 17});
db.Quote.create({text: "By having software replace hardware, the interface became fluid and flexible.", BookId: 17});
db.Quote.create({text: "\“The main thing I stressed was focus. Figure out what Google wants to be when it grows up.\” - Steve Jobs", BookId: 17});
db.Quote.create({text: "\“I figured that it was always my job to make sure that the team was excellent, and if I didn’t do it, nobody was going to do it.\” - Steve Jobs", BookId: 17});
db.Quote.create({text: "\“That’s always what I’ve tried to do – keep moving. Otherwise, as Dylan says, if you’re not busy being born, you’re busy dying.\” - Steve Jobs", BookId: 17});
db.Quote.create({text: "\“We try to use the talents we do have to express our deep feelings, to show our appreciation of all the contributions that came before us, and to add something to that flow.\” - Steve Jobs", BookId: 17});
db.Quote.create({text: "The Rules of Improvisation That Will Change Your Life and Reduce Belly Fat: The first rule of improvisation is AGREE. Always agree and SAY YES...Now, obviously in real life you’re not always going to agree with everything everyone says. But the Rule of Agreement reminds you to “respect what your partner has created” and to at least start from an open-minded place. Start with a YES and see where that takes you...As an improvisor, I always find it jarring when I meet someone in real life whose first answer is no...What kind of way is that to live? The second rule of improvisation is not only to say yes, but YES, AND. You are supposed to agree and then add something of your own...To me YES, AND means don’t be afraid to contribute. It’s your responsibility to contribute. Always make sure you’re adding something to the discussion. Your initiations are worthwhile. The next rule is MAKE STATEMENTS. This is a positive way of saying “Don’t ask questions all the time.”...In other words: Whatever the problem, be part of the solution. Don’t just sit around raising questions and pointing out obstacles. We’ve all worked with that person. That person is a drag. THERE ARE NO MISTAKES, only opportunities...In improv there are no mistakes, only beautiful happy accidents. And many of the world’s greatest discoveries have been by accident. I mean, look at the Reese’s Peanut Butter Cup, or Botox.", BookId: 18});
db.Quote.create({text: "You have to try your hardest to be at the top of your game and improve every joke you can until the last possible second, and then have to let it go.", BookId: 18});
db.Quote.create({text: "Never cut to a closed door.", BookId: 18});
db.Quote.create({text: "Comedy is about confidence, and the moment an audience senses a slip in confidence, they’re nervous for you and can’t laugh...Make the entrance well-timed and exciting...There’s no harm in things looking fun, and you don’t get extra credit for keeping things indie and grim.", BookId: 18});
db.Quote.create({text: "Don’t hire anyone you wouldn’t want to run into in the hallway at three in the morning.", BookId: 18});
db.Quote.create({text: "She wasn’t there to play wives and girlfriends in the boys’ scenes. She was there to do what she wanted to do and she did not fucking care if you like it...”Is this person in between me and what I want to do?” If the answer is no, ignore it and move on. Your energy is better used doing your work and outpacing people that way. Then, when you’re in charge, don’t hire the people who were jerky to you.", BookId: 18});
db.Quote.create({text: "If your boss is a jerk, try to find someone above or around your boss who is not a jerk...Again, don’t waste your energy trying to educate or change opinions. Go “Over! Under! Through!” and opinions will change organically when you’re the boss.", BookId: 18});
db.Quote.create({text: "Do your thing and don’t care if they like it.", BookId: 18});
db.Quote.create({text: "In an attempt to make things easier for myself, which is the basis for all of history’s worst decisions.", BookId: 18});
db.Quote.create({text: "Iskiate - It’s brewed up by dissolving chia seeds in water with a little sugar and squirt of lime.", BookId: 19});
db.Quote.create({text: "\“Make friends with pain, and you will never be alone.\” - Ken Chlouber", BookId: 19});
db.Quote.create({text: "\“To move into the lead means making an act requiring fierceness and confidence. But fear must play some part...no relaxation is possible, and all discretion is thrown to the wind.\” - Roger Bannister", BookId: 19});
db.Quote.create({text: "Glee and determination are usually antagonistic emotions, yet the Tarahumara were brimming with both at once, as if running to the death made them feel more alive.", BookId: 19});
db.Quote.create({text: "\“There are two goddesses in your heart, the Goddess of Wisdom and the Goddess of Wealth. Everyone thinks they need to get wealth first, and wisdom will come. So they concern themselves with chasing money. But they have it backwards. You have to give your heart to the Goddess of Wisdom, give her all your love and attention, and the Goddess of Wealth will become jealous and follow you.\” - Dr. Joe Vigil", BookId: 19});
db.Quote.create({text: "\“Let us live so that when we come to die, even the undertaker will be sorry.\” - Mark Twain", BookId: 19});
db.Quote.create({text: "\“Think Easy, Light, Smooth, and Fast. You start with easy, because if that’s all you get, that’s not so bad. Then work on light. Make it effortless, like you don’t give a shit how high the hill is or how far you’ve got to go. When you’ve practiced that so long that you forget you’re practicing, you work on making it smoooooooth. You won’t have to worry about the last one – you get those three, and you’ll be fast.\” - El Caballo Blanco", BookId: 19});
db.Quote.create({text: "You can’t hate the Beast and expect to beat it. The only way to truly conquer something, as every great philosopher and geneticist will tell you, is to love it.", BookId: 19});
db.Quote.create({text: "They were expected to accomplish nothing, so they could try anything. Audacity beckoned.", BookId: 19});
db.Quote.create({text: "...running barefoot on dewy grass three times a week.", BookId: 19});
db.Quote.create({text: "\“Every great cause begins as a movement, becomes a business, and turns into a racket.\” - Eric Hoffer", BookId: 19});
db.Quote.create({text: "...you’ll be up on your forefeet, with your back erect, head steady, arms high, elbows driving, and feet touching down quickly on the forefoot and kicking back toward your butt.", BookId: 19});
db.Quote.create({text: "You can’t run uphill powerfully with poor biomechanics.", BookId: 19});
db.Quote.create({text: "\“Poetry, music, forests, oceans, solitude – they were what developed enormous spiritual strength. I came to realize that spirit, as much or more than physical conditioning, had to be stored up before a race.\” - Herb Elliott", BookId: 19});
db.Quote.create({text: "1 Reduce - The simplest way to achieve simplicity is through thoughtful reduction. 2 Organize - Organization makes a system of many appear fewer. 3 Time - Savings in time feel like simplicity. 4 Learn - Knowledge makes everything simpler. 5 Differences - Simplicity and complexity need each other. 6 Context - What lies in the periphery of simplicity is definitely not peripheral. 7 Emotion - More emotions are better than less. 8 Trust - In simplicity we trust. 9 Failure - Some things can never be made simple. 10 The One - Simplicity is about subtracting the obvious, and adding the meaningful.", BookId: 20});
db.Quote.create({text: "How simple can you make it? / How complex does it have to be?", BookId: 20});
db.Quote.create({text: "Organization makes a system of many appear fewer.", BookId: 20});
db.Quote.create({text: "Savings in time feel like simplicity.", BookId: 20});
db.Quote.create({text: "...can also make up for what is lost by embodying what is most important in subtle ways.", BookId: 20});
db.Quote.create({text: "How can you make the wait shorter? / How can you make the wait more tolerable?", BookId: 20});
db.Quote.create({text: "Basics are the beginning. Repeat yourself often. Avoid creating desperation. Inspire with examples. Never forget to repeat yourself.", BookId: 20});
db.Quote.create({text: "Observing what fails to make sense to the non-expert, and then following that trail successively to the very end of the knowledge chain is the critical path to success.", BookId: 20});
db.Quote.create({text: "Repetition works.", BookId: 20});
db.Quote.create({text: "A gentle, inspired start is the best way.", BookId: 20});
db.Quote.create({text: "The practice of education is the highest form of intellectual philanthropy.", BookId: 20});
db.Quote.create({text: "RELATE-TRANSLATE-SURPRISE relies on having a common experience upon which to map your own, which unfortunately limits the approach to specific cultures and customs.", BookId: 20});
db.Quote.create({text: "Difficult tasks seem easier when they are ‘need to know’ rather than ‘nice to know.’", BookId: 20});
db.Quote.create({text: "At the core of the best rewards is this fundamental desire for freedom in thinking, living and being.", BookId: 20});
db.Quote.create({text: "Simplicity and complexity need each other.", BookId: 20});
db.Quote.create({text: "We know how to appreciate something better when we can compare it to something else.", BookId: 20});
db.Quote.create({text: "I am now more careful to feel the precious rhythm of each year of life. I hear the beat of simplicity and complexity quite clearly in everything that I experience.", BookId: 20});
db.Quote.create({text: "\“Become a light bulb instead of a laser beam.\” - Nicholas Negroponte", BookId: 20});
db.Quote.create({text: "That which appears to be of immediate relevance may not be nearly as important compared to everything else around.", BookId: 20});
db.Quote.create({text: "When there is less, we appreciate everything much more.", BookId: 20});
db.Quote.create({text: "Ambience is the proverbial ‘secret sauce’ to any great meal or memorable interaction.", BookId: 20});
db.Quote.create({text: "Synthesizing the ambient experience of simplicity requires attention to everything that seemingly does not matter.", BookId: 20});
db.Quote.create({text: "How directed can I stand to feel? / How directionless can I afford to be?", BookId: 20});
db.Quote.create({text: "Form follows function...feeling follows form.", BookId: 20});
db.Quote.create({text: "Aichaku (love-fit) describes a deeper kind of emotional attachment that a person can feel for an object. It is a kind of symbiotic love for an object that deserves affection not for what it does, but for what it is.", BookId: 20});
db.Quote.create({text: "The goal of LEAN BACK is to achieve relaxation as the desired state.", BookId: 20});
db.Quote.create({text: "\“To craft a good story, take the best of two extremes – fantasy and believability – and find a way to merge them.\” - Disney Pixar", BookId: 20});
db.Quote.create({text: "\“Deprived of support in our environment and the support of our own bodies, the only thing propping us up was our belief in accomplishing the mission—complete Hell Week. In psychology this belief is called self-efficacy. Even when the mission seems impossible, it is the strength of our belief that makes success possible. The absence of this belief guarantees failure. A strong belief in the mission fuels our ability to focus, put forth effort, and persist. Believing allows us to see the goal (complete Hell Week) and break the goal down into more manageable objectives (one evolution at a time). If the evolution is a boat race, it can be broken down into even smaller objectives such as paddling. Believing allows us to seek out strategies to accomplish the objectives, such as using the larger shoulder muscles to paddle rather than the smaller forearm muscles. Then, when the race is done, move on to the next evolution. Thinking too much about what happened and what is about to happen will wear you down. Live in the moment and take it one step at a time.\” - Howard E. Wasdin, Navy SEAL", BookId: 20});
db.Quote.create({text: "\“As long as I can enjoy something other people can enjoy it too\” - Miyamoto, head of Nintendo", BookId: 20});
db.Quote.create({text: "\“What we demand in development is kyokan.  Kyo is the sharing and kan is the emotional feeling.\” - Miyamoto, head of Nintendo", BookId: 20});
db.Quote.create({text: "\"It's not about what you've done,\" he said. \"It's about the process and journey of what you've accomplished, the gratification you get from it, and what you learned from it. After that, it's over. And it's time for the next one. That's how you have to think.\" - Tom Brady", BookId: 20});
db.Quote.create({text: "The person who knows ‘how’ will always have a job. The person who knows ‘why’ will always be his boss.", BookId: 21});
db.Quote.create({text: "I am just a common man who is true to his beliefs.", BookId: 21});
db.Quote.create({text: "Never lie. Never cheat. Never steal. Don’t whine. Don’t complain. Don’t make excuses.", BookId: 21});
db.Quote.create({text: "Seven Things To Do: 1) Be true to yourself. 2) Help others. 3) Make each day your masterpiece. 4) Drink deeply from good books. 5) Make friendship a fine art. 6) Build a shelter against a rainy day. 7) Pray for guidance and count and give thanks for your blessings every day.", BookId: 21});
db.Quote.create({text: "How much more pleasant this world would be if we magnified our blessings the way we magnify our dissapointments.", BookId: 21});
db.Quote.create({text: "I am not what I ought to be, Not what I want to be, Not what I am going to be, But I am thankful that, I am better than I used to be.", BookId: 21});
db.Quote.create({text: "Never believe you’re better than anybody else, but remember that you’re just as good as everybody else.", BookId: 21});
db.Quote.create({text: "No better, just as good.", BookId: 21});
db.Quote.create({text: "\"No person was ever honored for what he received. Honor has been the reward for what he gave.\" – Calvin Coolidge", BookId: 21});
db.Quote.create({text: "I also believe that things turn out best for those who make the best of the way things turn out.", BookId: 21});
db.Quote.create({text: "\"Try not to become a man of success but rather try to become a man of value.\" – Albert Einstein", BookId: 21});
db.Quote.create({text: "How his company’s people work as a team is the product. Shoes are the by-product.", BookId: 21});
db.Quote.create({text: "You always win when you make the full effort to do the best of which you’re capable.", BookId: 21});
db.Quote.create({text: "When you blame others you are trying to excuse yourself. When you make excuses you can’t properly evaluate yourself. Without proper self-evaluation, failure is inevitable.", BookId: 21});
db.Quote.create({text: "Learn from the past. Don’t live in the past.", BookId: 21});
db.Quote.create({text: "Mix idealism with realism and add hard work.", BookId: 21});
db.Quote.create({text: "Understand there is a price to be paid for achieving anything of significance. You must be willing to pay the price.", BookId: 21});
db.Quote.create({text: "Eight Suggestions For Succeeding: 1) Fear no opponent. Respect every opponent. 2) Remember, it’s the perfection of the smallest details that make big things happen. 3) Keep in mind that hustle makes up for many a mistake. 4) Be more interested in character than reputation. 5) Be quick, but don’t hurry. 6) Understand that the harder you work, the more luck you will have. 7) Know that valid self-analysis is crucial for improvement. 8) Remember that there is no substitute for hard work and careful planning. Failing to prepare is preparing to fail.", BookId: 21});
db.Quote.create({text: "\"The team that makes the most mistakes will probably win.\" – Piggy Lambert", BookId: 21});
db.Quote.create({text: "Nine Promises That Can Bring Happiness: 1) Promise yourself that you will talk health, happiness and prosperity as often as possible. 2) Promise yourself to make all your friends know there is something in them that is special and that you value. 3) Promise to think only of the best, to work only for the best, and to expect only the best in yourself and others. 4) Promise to be just as enthusiastic about the success of others as you are about your own. 5) Promise yourself to be so strong that nothing can disturb your peace of mind. 6) Promise to forget the mistakes of the past and press on to greater achievements in the future. 7) Promise to wear a cheerful appearance at all times and give every person you meet a smile. 8) Promise to give so much time to improving yourself that you have no time to criticize others. 9) Promise to be too large for worry, too noble for anger, too strong for fear, and too happy to permit trouble to press on you.", BookId: 21});
db.Quote.create({text: "To worry about whether what I’m building is going to be better than what somebody else is building elsewhere is to worry needlessly. I believe that if I’m worried about what’s going on outside, it will detract from my preparation inside.", BookId: 21});
db.Quote.create({text: "Failure is not fatal, but failure to change might be.", BookId: 21});
db.Quote.create({text: "Looking back it seems to me, All the grief that had to be. Left me when the pain was o’er. Stronger than I was before", BookId: 21});
db.Quote.create({text: "Remember this your lifetime through – Tomorrow, there will be more to do. And failure waits for all who stay. With some success made yesterday. Tomorrow, you must try once more And even harder than before.", BookId: 21});
db.Quote.create({text: "You must never stand still. You’re either moving upward a little bit or you’re going the other way. You can’t expect to go upward too quickly, but you can sure go down very quickly.", BookId: 21});
db.Quote.create({text: "\"In great attempts it is glorious even to fail.\" – Wilfred A. Peterson", BookId: 21});
db.Quote.create({text: "You must have respect, which is a part of love, for those under your supervision. They they will do what you ask and more.", BookId: 21});
db.Quote.create({text: "Fairness is giving all people the treatment they earn and deserve. It doesn’t mean treating everyone alike. That’s unfair, because everyone doesn’t earn the same treatment.", BookId: 21});
db.Quote.create({text: "The only goal of criticism or discipline is improvement.", BookId: 21});
db.Quote.create({text: "This defines a leader; if you can’t teach and you can’t motivate, you can’t lead.", BookId: 21});
db.Quote.create({text: "Focus all your effort on what is within your power to control.", BookId: 21});
db.Quote.create({text: "Seek the small improvement one day at a time. That’s the only way it happens – and when it happens, it lasts.", BookId: 21});
db.Quote.create({text: "If you get caught up in things over which you have no control, it will adversely affect those things over which you have control.", BookId: 21});
db.Quote.create({text: "Talent is God-given: be humble. Fame is man-given: be thankful. Conceit is self-given: be careful.", BookId: 21});
db.Quote.create({text: "People learn more effectively if information is given in bite-size amounts rather than everything all at once.", BookId: 21});
db.Quote.create({text: "Choose your role models, your leaders, your teachers and coaches, with care.", BookId: 21});
db.Quote.create({text: "There is a choice you have to make, in everything you do. And you must always keep in mind the choice you make, makes you.", BookId: 21});
db.Quote.create({text: "\"You wonder how they do it, You look to see the knack, You watch the foot in action, Or the shoulder or the back. But when you spot the answer. Where the higher glamours lurk, You’ll find in moving higher. Up the laurel-covered spire, That most of it is practice, And the rest of it is work.\" – Grantland Rice", BookId: 21});
db.Quote.create({text: "Both must give for there to be friendship...Be brave enough to offer friendship.", BookId: 21});
db.Quote.create({text: "If you’re afraid of failure, you will never do the things you are capable of doing.", BookId: 21});
db.Quote.create({text: "You must believe in yourself if you expect others to believe in you.", BookId: 21});
db.Quote.create({text: "Good things always take time, and that requires patience.", BookId: 21});
db.Quote.create({text: "If you are through learning, you are through.", BookId: 21});
db.Quote.create({text: "If you do not have the time to do it right, when will you find the time to do it over?", BookId: 21});
db.Quote.create({text: "The man who is afraid to risk failure seldom has to face success.", BookId: 21});
db.Quote.create({text: "Be most interested in finding the best way, not in having your own way.", BookId: 21});
db.Quote.create({text: "Never make excuses. Your friends don’t need them and your foes won’t believe them.", BookId: 21});
db.Quote.create({text: "Never be disagreeable just because you disagree.", BookId: 21});
db.Quote.create({text: "Be slow to criticize and quick to commend.", BookId: 21});
db.Quote.create({text: "Do not mistake activity for achievement.", BookId: 21});
db.Quote.create({text: "Forget favors given; remember those received.", BookId: 21});
